[package]
name = "scallop"
version = "0.0.3"
description = "Wrapper library for bash"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["bash", "shell"]
autotests = false
exclude = [
	"bash/doc/*",
	"bash/examples/*",
	"bash/po/*",
	"bash/tests/*",
]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "scallop"
path = "src/lib.rs"

[[example]]
name = "scallop"

[dependencies]
bitflags = "1.3"
nix = "0.26"
once_cell = "1.8.0"
thiserror = "1.0.30"
tracing = "0.1"

[build-dependencies]
autotools = "0.2.4"
bindgen = "0.63"
camino = "1"
num_cpus = "1.0"

[dev-dependencies]
ctor = "0.1.22"
tempfile = "3"
