[package]
name = "scallop"
version = "0.0.9"
description = "Wrapper library for bash"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["bash", "shell"]
autotests = false
exclude = [
	"bash/doc/*",
	"bash/examples/*",
	"bash/po/*",
	"bash/tests/*",
]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "scallop"
path = "src/lib.rs"

[[example]]
name = "scallop"

[dependencies]
bitflags = "2.4.0"
ipc-channel = "0.17.0"
libc = "0.2.147"
nix = { version = "0.27.1", features = ["fs", "mman", "process", "signal"] }
once_cell = "1.18.0"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
tracing = "0.1.37"

[build-dependencies]
autotools = "0.2.6"
bindgen = "0.66.1"
camino = "1.1.6"
num_cpus = "1.16.0"

[dev-dependencies]
ctor = "0.2.4"
tempfile = "3.8.0"
