[package]
name = "scallop"
version = "0.0.4"
description = "Wrapper library for bash"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["bash", "shell"]
autotests = false
exclude = [
	"bash/doc/*",
	"bash/examples/*",
	"bash/po/*",
	"bash/tests/*",
]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "scallop"
path = "src/lib.rs"

[[example]]
name = "scallop"

[dependencies]
bitflags = "1.3.2"
nix = "0.26.2"
once_cell = "1.17.0"
thiserror = "1.0.38"
tracing = "0.1.37"

[build-dependencies]
autotools = "0.2.5"
bindgen = "0.63.0"
camino = "1.1.2"
num_cpus = "1.15.0"

[dev-dependencies]
ctor = "0.1.26"
tempfile = "3.3.0"
