[package]
name = "scallop"
version = "0.0.9"
description = "Wrapper library for bash"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/scallop"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["bash", "shell"]
autotests = false
exclude = [
	"bash/doc/*",
	"bash/examples/*",
	"bash/po/*",
	"bash/tests/*",
]
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "scallop"
path = "src/lib.rs"

[[example]]
name = "scallop"

[dependencies]
bitflags = "2.3.2"
ipc-channel = "0.16.1"
libc = "0.2.146"
nix = "0.26.2"
once_cell = "1.18.0"
serde = { version = "1.0.164", features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"

[build-dependencies]
autotools = "0.2.6"
bindgen = "0.66.1"
camino = "1.1.4"
num_cpus = "1.15.0"

[dev-dependencies]
ctor = "0.2.2"
tempfile = "3.6.0"
