[package]
name = "pkgcraft"
version = "0.0.2"
description = "library of Gentoo functionality"
authors = ["Tim Harder <radhermit@gmail.com>"]
homepage = "https://github.com/pkgcraft/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft"
readme = "README.md"
license = "MIT"
edition = "2021"
rust-version = "1.56"
autotests = false

[lib]
name = "pkgcraft"
path = "src/lib.rs"

[features]
git = ["git2"]

[dependencies]
async-trait = "0.1.51"
cached = "0.30"
chic = "1"
flate2 = "1.0"
futures = "0.3.16"
git2 = { version = "0.13", optional = true }
glob = "0.3.0"
indexmap = { version = "1.7.0", features = ["serde"] }
is_executable = "1.0.1"
itertools = "0.10.3"
once_cell = "1.8.0"
peg = "0.8"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream"] }
scallop = { path = "../scallop", version = "0.0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.9.4"
tar = "0.4.38"
tempfile = "3"
thiserror = "1.0.26"
tokio = { version = "1.14", features = ["full"] }
toml = "0.5.8"
tracing = "0.1"

[dev-dependencies]
criterion = "0.3"
gag = "1.0.0"
maplit = "1.0.2"
rusty-fork = "0.3.0"

[[bench]]
name = "bench"
harness = false
