[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Tim Harder <radhermit@gmail.com>"]
edition = "2021"
rust-version = "1.65"

[profile.bundled]
inherits = "release"
strip = "symbols"
