[package]
name = "arcanist-cli"
version = "0.0.1"
description = "Gentoo Linux mangling tool"
authors = ["Tim Harder <radhermit@gmail.com>"]
license = "MIT"
edition = "2018"

[[bin]]
bench = false
path = "src/main.rs"
name = "arc"

[dependencies]
arcanist = { path = "../lib" }
