[package]
name = "arcanist"
version = "0.0.5"
description = "package-building daemon leveraging pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/arcanist"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/arcanist"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.3"
clap = { version = "4", default-features = false, features = ["std", "suggestions"] }
config = { version = "0.13", default-features = false, features = ["toml"] }
futures = "0.3.25"
pkgcraft = { path = "../pkgcraft", version = "0.0.5" }
prost = "0.11"
regex = "1.7.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1.24", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tonic = { version = "0.8.3", features = ["tls", "gzip"] }
url = "2"

# pakt specific deps
log = "0.4"
once_cell = "1.17.0"
tracing = "0.1"
tracing-subscriber = "0.3.16"
tower = "0.4.13"

[build-dependencies]
tonic-build = "0.8.4"

[dev-dependencies]
assert_cmd = "2"
regex = "1"
tempfile = "3"

[lib]
name = "arcanist"
path = "src/lib/lib.rs"

[[bin]]
bench = false
path = "src/server/main.rs"
name = "arcanist"

[[bin]]
bench = false
path = "src/cli/main.rs"
name = "pakt"

[[test]]
name = "integration"
path = "tests/lib.rs"
