[package]
name = "arcanist"
version = "0.0.5"
description = "package-building daemon leveraging pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/arcanist"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/arcanist"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.70"
async-stream = "0.3.5"
clap = { version = "4.2.4", default-features = false, features = ["std", "suggestions"] }
config = { version = "0.13.3", default-features = false, features = ["toml"] }
futures = "0.3.28"
pkgcraft = { path = "../pkgcraft", version = "0.0.7" }
prost = "0.11.9"
regex = "1.8.0"
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0.40"
tokio = { version = "1.27", features = ["full"] }
tokio-stream = { version = "0.1.12", features = ["net"] }
tonic = { version = "0.9.2", features = ["tls", "gzip"] }
url = "2.3.1"

# pakt specific deps
once_cell = "1.17.1"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tower = "0.4.13"

[build-dependencies]
tonic-build = "0.9.2"

[dev-dependencies]
assert_cmd = "2.0.11"
regex = "1.8.0"
tempfile = "3.5.0"

[lib]
name = "arcanist"
path = "src/lib/lib.rs"

[[bin]]
bench = false
path = "src/server/main.rs"
name = "arcanist"

[[bin]]
bench = false
path = "src/cli/main.rs"
name = "pakt"

[[test]]
name = "integration"
path = "tests/lib.rs"
