[package]
name = "arcanist"
version = "0.0.5"
description = "package-building daemon leveraging pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/arcanist"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/arcanist"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.80"
async-stream = "0.3.5"
clap = { version = "4.5.1", default-features = false, features = ["std", "suggestions"] }
config = { version = "0.14.0", default-features = false, features = ["toml"] }
futures = "0.3.30"
pkgcraft = { path = "../pkgcraft", version = "0.0.14" }
prost = "0.12.3"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.57"
tokio = { version = "1.36", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
tonic = { version = "0.11.0", features = ["tls", "gzip"] }
url = "2.5.0"

# pakt specific deps
once_cell = "1.19.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tower = "0.4.13"

[build-dependencies]
tonic-build = "0.11.0"

[dev-dependencies]
assert_cmd = "2.0.14"
regex = "1.10.3"
tempfile = "3.10.1"

[lib]
name = "arcanist"
path = "src/lib/lib.rs"

[[bin]]
bench = false
path = "src/server/main.rs"
name = "arcanist"

[[bin]]
bench = false
path = "src/cli/main.rs"
name = "pakt"

[[test]]
name = "integration"
path = "tests/lib.rs"
