[package]
name = "pkgcraft"
version = "0.0.17"
description = "library of Gentoo functionality"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "pkgcraft"

[features]
default = []
# enable git repo syncing support
git = ["dep:git2"]
# enable repo syncing over https, e.g. tar+https
https = ["dep:flate2", "dep:reqwest", "dep:tar", "dep:tokio"]
# external test support
test = ["dep:assert_cmd"]

[dependencies]
blake2 = "0.10.6"
blake3 = { version = "1.5.3", features = ["traits-preview"] }
cached = "0.53.1"
camino = { version = "1.1.7", features = ["serde1"] }
chic = "1.2.2"
clap = { version = "4.5.14", features = ["derive"] }
crossbeam-channel = "0.5.13"
digest = "0.10.7"
enum-as-inner = "0.6.0"
filetime = "0.2.24"
flate2 = { version = "1.0.31", optional = true }
futures = "0.3.30"
git2 = { version = "0.19.0", optional = true }
glob = "0.3.1"
hex = "0.4.3"
indexmap = { version = "2.3.0", features = ["rayon", "serde"] }
indicatif = "0.17.8"
indoc = "2.0.5"
is_executable = "1.0.1"
itertools = "0.13.0"
md-5 = "0.10.6"
nix = { version = "0.29.0", features = ["user"] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
peg = "0.8.4"
rayon = "1.10.0"
regex = "1.10.6"
reqwest = { version = "0.12.5", default-features = false, features = ["rustls-tls", "stream"], optional = true }
roxmltree = "0.20.0"
rust-ini = "0.21.1"
scallop = { path = "../scallop", version = "0.0.17" }
serde = { version = "1.0.205", features = ["derive"] }
serde_with = { version = "3.9.0", default-features = false, features = ["macros"] }
sha2 = "0.10.8"
strum = { version = "0.26.3", features = ["derive"] }
tar = { version = "0.4.41", optional = true }
tempfile = "3.12.0"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"], optional = true }
toml = "0.8.19"
tracing = "0.1.40"
walkdir = "2.5.0"

# exported test support deps
assert_cmd = { version = "2.0.16", optional = true }

[dev-dependencies]
criterion = "0.5"
ctor = "0.2.8"
serde_json = "1.0.122"
tracing-test = "0.2.5"

[[bench]]
name = "bench"
harness = false
