[package]
name = "pkgcraft"
version = "0.0.15"
description = "library of Gentoo functionality"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "pkgcraft"

[features]
default = []
# enable git repo syncing support
git = ["dep:git2"]
# enable repo syncing over https, e.g. tar+https
https = ["dep:flate2", "dep:reqwest", "dep:tar", "dep:tokio"]
# external test support
test = ["dep:assert_cmd"]

[dependencies]
blake2 = "0.10.6"
blake3 = { version = "1.5.1", features = ["traits-preview"] }
cached = "0.51.3"
camino = { version = "1.1.6", features = ["serde1"] }
chic = "1.2.2"
clap = { version = "4.5.4", features = ["derive"] }
crossbeam-channel = "0.5.12"
digest = "0.10.7"
enum-as-inner = "0.6.0"
filetime = "0.2.23"
flate2 = { version = "1.0.30", optional = true }
futures = "0.3.30"
git2 = { version = "0.18.3", optional = true }
glob = "0.3.1"
hex = "0.4.3"
indexmap = { version = "2.2.6", features = ["rayon", "serde"] }
indicatif = "0.17.8"
indoc = "2.0.5"
is_executable = "1.0.1"
itertools = "0.12.1"
md-5 = "0.10.6"
nix = { version = "0.28.0", features = ["user"] }
num_cpus = "1.16.0"
once_cell = "1.19.0"
peg = "0.8.3"
rayon = "1.10.0"
regex = "1.10.4"
reqwest = { version = "0.12.4", default-features = false, features = ["rustls-tls", "stream"], optional = true }
roxmltree = "0.19.0"
rust-ini = "0.21.0"
scallop = { path = "../scallop", version = "0.0.15" }
serde = { version = "1.0.201", features = ["derive"] }
serde_with = { version = "3.8.1", default-features = false, features = ["macros"] }
sha2 = "0.10.8"
strum = { version = "0.26.2", features = ["derive"] }
tar = { version = "0.4.40", optional = true }
tempfile = "3.10.1"
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["full"], optional = true }
toml = "0.8.12"
tracing = "0.1.40"
walkdir = "2.5.0"

# exported test support deps
assert_cmd = { version = "2.0.14", optional = true }

[dev-dependencies]
criterion = "0.5"
ctor = "0.2.8"
tracing-test = "0.2.4"

[[bench]]
name = "bench"
harness = false
