[package]
name = "pkgcraft"
version = "0.0.7"
description = "library of Gentoo functionality"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "pkgcraft"
path = "src/lib.rs"

[[bin]]
name = "pk"
bench = false
required-features = ["tools"]

[features]
default = []
# enable git repo syncing support
git = ["dep:git2"]
# enable repo syncing over https, e.g. tar+https
https = ["dep:flate2", "dep:reqwest", "dep:tar", "dep:tokio"]
# build command-line tools
tools = ["dep:aho-corasick", "dep:anyhow", "dep:is-terminal"]
# export test support for integration tests
test = ["dep:assert_cmd"]

[dependencies]
async-trait = "0.1.68"
blake2 = "0.10.6"
blake3 = "1.3.3"
cached = "0.43.0"
camino = { version = "1.1.4", features = ["serde1"] }
chic = "1.2.2"
clap = { version = "4.2.5", features = ["derive"] }
crossbeam-channel = "0.5.8"
enum-as-inner = "0.5.1"
filetime = "0.2.21"
flate2 = { version = "1.0.26", optional = true }
futures = "0.3.28"
git2 = { version = "0.17.1", optional = true }
glob = "0.3.1"
hex = "0.4.3"
indexmap = { version = "1.9.3", features = ["serde"] }
indoc = "2.0.1"
is_executable = "1.0.1"
itertools = "0.10.5"
nix = "0.26.2"
once_cell = "1.17.1"
peg = "0.8.1"
regex = "1.8.1"
reqwest = { version = "0.11.17", default-features = false, features = ["rustls-tls", "stream"], optional = true }
roxmltree = "0.18.0"
rust-ini = "0.18.0"
scallop = { path = "../scallop", version = "0.0.5" }
serde = { version = "1.0.160", features = ["derive"] }
serde_with = { version = "2.3.3", default-features = false, features = ["macros"] }
sha2 = "0.10.6"
strum = { version = "0.24.1", features = ["derive"] }
sys-info = "0.9.1"
tar = { version = "0.4.38", optional = true }
tempfile = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["full"], optional = true }
toml = "0.7.3"
tracing = "0.1.37"
walkdir = "2.3.3"

# pk dependencies
aho-corasick = { version = "1.0.1", optional = true }
anyhow = { version = "1.0.71", optional = true }
is-terminal = { version = "0.4.7", optional = true }

# test feature dependencies
assert_cmd = { version = "2.0.11", optional = true }

[dev-dependencies]
assert_cmd = "2.0.11"
criterion = "0.4"
ctor = "0.2.0"
maplit = "1.0.2"
predicates = "3.0.3"
tracing-test = "0.2.4"

[[bench]]
name = "bench"
harness = false

[[test]]
name = "pk"
path = "tests/pk/pk.rs"
