[package]
name = "pkgcraft"
version = "0.0.8"
description = "library of Gentoo functionality"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "pkgcraft"
path = "src/lib.rs"

[features]
default = []
# enable git repo syncing support
git = ["dep:git2"]
# enable repo syncing over https, e.g. tar+https
https = ["dep:flate2", "dep:reqwest", "dep:tar", "dep:tokio"]

[dependencies]
async-trait = "0.1.68"
blake2 = "0.10.6"
blake3 = { version = "1.3.3", features = ["traits-preview"] }
cached = "0.44.0"
camino = { version = "1.1.4", features = ["serde1"] }
chic = "1.2.2"
clap = { version = "4.3.2", features = ["derive"] }
crossbeam-channel = "0.5.8"
digest = "0.10.7"
enum-as-inner = "0.6.0"
filetime = "0.2.21"
flate2 = { version = "1.0.26", optional = true }
futures = "0.3.28"
git2 = { version = "0.17.2", optional = true }
glob = "0.3.1"
hex = "0.4.3"
indexmap = { version = "1.9.3", features = ["serde"] }
indoc = "2.0.1"
is_executable = "1.0.1"
itertools = "0.10.5"
md-5 = "0.10.5"
nix = "0.26.2"
num_cpus = { version = "1.15.0", optional = true }
once_cell = "1.18.0"
peg = "0.8.1"
rayon = "1.7.0"
regex = "1.8.4"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "stream"], optional = true }
roxmltree = "0.18.0"
rust-ini = "0.19.0"
scallop = { path = "../scallop", version = "0.0.7" }
serde = { version = "1.0.163", features = ["derive"] }
serde_with = { version = "3.0.0", default-features = false, features = ["macros"] }
sha2 = "0.10.6"
strum = { version = "0.24.1", features = ["derive"] }
sys-info = "0.9.1"
tar = { version = "0.4.38", optional = true }
tempfile = "3.6.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"], optional = true }
toml = "0.7.4"
tracing = "0.1.37"
walkdir = "2.3.3"

# exported test support deps
assert_cmd = "2.0.11"

[dev-dependencies]
criterion = "0.5"
ctor = "0.2.2"
tracing-test = "0.2.4"

[[bench]]
name = "bench"
harness = false
