[package]
name = "pkgcraft-tools"
version = "0.0.10"
description = "pkgcraft-based tools for Gentoo"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pk"
bench = false

[features]
# flaky tests that aren't run by default
flaky = []

[dependencies]
aho-corasick = "1.0.2"
anyhow = "1.0.71"
camino = "1.1.6"
clap = { version = "4.3.11", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
humantime = "2.1.0"
indexmap = { version = "2.0.0", features = ["serde"] }
is-terminal = "0.4.9"
itertools = "0.11.0"
num_cpus = "1.16.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.10" }
scallop = { path = "../scallop", version = "0.0.9" }
strum = { version = "0.25.0", features = ["derive"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"

[dev-dependencies]
ctor = "0.2.4"
indoc = "2.0.2"
predicates = "3.0.3"

[[test]]
name = "pk"
path = "tests/pk/pk.rs"
