[package]
name = "pkgcraft-tools"
version = "0.0.12"
description = "pkgcraft-based tools for Gentoo"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pk"
bench = false

[features]
# flaky tests that aren't run by default
flaky = []

[dependencies]
aho-corasick = "1.1.1"
anyhow = "1.0.75"
camino = "1.1.6"
clap = { version = "4.4.6", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
humantime = "2.1.0"
indexmap = { version = "2.0.2", features = ["serde"] }
itertools = "0.11.0"
num_cpus = "1.16.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.12" }
scallop = { path = "../scallop", version = "0.0.11" }
strum = { version = "0.25.0", features = ["derive"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"

[dev-dependencies]
indoc = "2.0.4"
predicates = "3.0.4"
pretty_assertions = "1.4.0"
walkdir = "2.4.0"

[[test]]
name = "pk"
path = "tests/pk/pk.rs"
