[package]
name = "pkgcraft-tools"
version = "0.0.8"
description = "pkgcraft-based tools for Gentoo"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pk"
bench = false

[dependencies]
aho-corasick = "1.0.2"
anyhow = "1.0.71"
clap = { version = "4.3.2", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
humantime = "2.1.0"
indexmap = { version = "1.9.3", features = ["serde"] }
indicatif = "0.17.5"
is-terminal = "0.4.7"
itertools = "0.10.5"
num_cpus = "1.15.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.8" }
scallop = { path = "../scallop", version = "0.0.7" }
strum = { version = "0.24.1", features = ["derive"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = "0.3.17"

[dev-dependencies]
predicates = "3.0.3"

[[test]]
name = "pk"
path = "tests/pk/pk.rs"
