[package]
name = "pkgcraft-tools"
version = "0.0.14"
description = "CLI tools based on pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pk"
bench = false

[features]
# flaky tests that aren't run by default
flaky = []
# test support
test = ["pkgcraft/test"]

[dependencies]
aho-corasick = "1.1.2"
anyhow = "1.0.79"
camino = "1.1.6"
clap = { version = "4.4.18", features = ["derive"] }
clap-verbosity-flag = "2.1.2"
humantime = "2.1.0"
indexmap = { version = "2.2.2", features = ["serde"] }
itertools = "0.12.1"
num_cpus = "1.16.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.14" }
scallop = { path = "../scallop", version = "0.0.13" }
strum = { version = "0.26.1", features = ["derive"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"

[dev-dependencies]
indoc = "2.0.4"
predicates = "3.1.0"
pretty_assertions = "1.4.0"
tempfile = "3.9.0"
walkdir = "2.4.0"

[[test]]
name = "pk"
