[package]
name = "pkgcraft-tools"
version = "0.0.17"
description = "CLI tools based on pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "pk"
bench = false

[features]
# flaky tests that aren't run by default
flaky = []
# test support
test = ["pkgcraft/test"]

[dependencies]
aho-corasick = "1.1.3"
anyhow = "1.0.93"
camino = "1.1.9"
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
humantime = "2.1.0"
indexmap = { version = "2.6.0", features = ["serde"] }
indoc = "2.0.5"
itertools = "0.13.0"
num_cpus = "1.16.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.17" }
scallop = { path = "../scallop", version = "0.0.17" }
strum = { version = "0.26.3", features = ["derive"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"

[dev-dependencies]
predicates = "3.1.2"
pretty_assertions = "1.4.1"
tempfile = "3.14.0"
walkdir = "2.5.0"

[[test]]
name = "pk"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ name }-{ version }/{ name }-{ version }-{ target }.tar.xz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "txz"
disabled-strategies = ["quick-install", "compile"]
