[package]
name = "pkgcraft-tools"
version = "0.0.20"
description = "CLI tools based on pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft-tools"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "pk"
bench = false

[[bin]]
name = "shell"
path = "src/bin/pk/shell.rs"
required-features = ["shell"]

[features]
# flaky tests that aren't run by default
flaky = []
# test support
test = ["pkgcraft/test"]
# shell completion support
shell = ["dep:clap_complete"]

[dependencies]
aho-corasick = "1.1.3"
anyhow = "1.0.93"
camino = "1.1.9"
clap = { version = "4.5.21", features = ["derive"] }
clap_complete = { version = "4.5.38", optional = true }
clap-verbosity-flag = "3.0.1"
crossbeam-channel = "0.5.13"
futures = "0.3.31"
humantime = "2.1.0"
indexmap = { version = "2.7.0", features = ["serde"] }
indicatif = "0.17.9"
indoc = "2.0.5"
itertools = "0.13.0"
num_cpus = "1.16.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.20" }
reqwest = { version = "0.12.9", default-features = false, features = ["hickory-dns", "rustls-tls", "socks", "stream"] }
scallop = { path = "../scallop", version = "0.0.19" }
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"

[dev-dependencies]
predicates = "3.1.2"
pretty_assertions = "1.4.1"
tempfile = "3.14.0"
walkdir = "2.5.0"

[[test]]
name = "pk"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ name }-{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "txz"
disabled-strategies = ["quick-install", "compile"]
