[package]
name = "pkgcruft"
version = "0.0.1"
description = "pkgcraft-based QA support for Gentoo"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcruft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcruft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
# enable git support
git = ["dep:git2"]
vendored-libgit2 = ["git2/vendored-libgit2"]
vendored-openssl = ["git2/vendored-openssl"]

[lib]
name = "pkgcruft"

[[bin]]
name = "pkgcruft"

[[bin]]
name = "pkgcruft-git-pre-push"
required-features = ["git"]

[dependencies]
anyhow = "1.0.78"
camino = "1.1.6"
clap = { version = "4.4.12", features = ["derive"] }
clap-verbosity-flag = "2.1.1"
crossbeam-channel = "0.5.10"
git2 = { version = "0.18.1", optional = true }
indexmap = { version = "2.1.0", features = ["serde"] }
itertools = "0.12.0"
num_cpus = "1.16.0"
once_cell = "1.19.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.13" }
scallop = { path = "../scallop", version = "0.0.12" }
strum = { version = "0.25.0", features = ["derive"] }
termcolor = "1.4.0"
thiserror = "1.0.53"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
