[package]
name = "pkgcruft"
version = "0.0.2"
description = "QA library and tools based on pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcruft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcruft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
# test support
test = ["dep:glob", "pkgcraft/test"]

[lib]
name = "pkgcruft"

[[bin]]
name = "pkgcruft"

[[test]]
name = "pkgcruft"

[[bench]]
name = "bench"
harness = false

[dependencies]
anyhow = "1.0.83"
camino = "1.1.6"
clap = { version = "4.5.4", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
colored = "2.1.0"
crossbeam-channel = "0.5.12"
indexmap = { version = "2.2.6", features = ["serde"] }
itertools = "0.12.1"
num_cpus = "1.16.0"
once_cell = "1.19.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.15" }
scallop = { path = "../scallop", version = "0.0.15" }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
strfmt = "0.2.4"
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.60"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"

# exported test support deps
glob = { version = "0.3.1", optional = true }

[dev-dependencies]
criterion = "0.5"
indoc = "2.0.5"
predicates = "3.1.0"
tempfile = "3.10.1"
