[package]
name = "pkgcruft"
version = "0.0.5"
description = "QA library and tools based on pkgcraft"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcruft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcruft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
# test support
test = ["dep:assert_cmd", "dep:glob", "pkgcraft/test"]

[lib]
name = "pkgcruft"

[[bin]]
name = "pkgcruft"

[[test]]
name = "pkgcruft"

[[bench]]
name = "bench"
harness = false

[dependencies]
anyhow = "1.0.93"
camino = "1.1.9"
clap = { version = "4.5.21", features = ["derive", "string"] }
clap-verbosity-flag = "3.0.0"
colored = "2.1.0"
crossbeam-channel = "0.5.13"
indexmap = { version = "2.6.0", features = ["serde"] }
indoc = "2.0.5"
itertools = "0.13.0"
num_cpus = "1.16.0"
pkgcraft = { path = "../pkgcraft", version = "0.0.18" }
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
strfmt = "0.2.4"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "2.0.3"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
tree-sitter = "0.24.4"
tree-sitter-bash = "0.23.3"

# exported test support deps
assert_cmd = { version = "2.0.16", optional = true }
glob = { version = "0.3.1", optional = true }

[dev-dependencies]
criterion = "0.5"
predicates = "3.1.2"
pretty_assertions = "1.4.1"
tempfile = "3.14.0"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ name }-{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "txz"
disabled-strategies = ["quick-install", "compile"]
