[package]
name = "pkgcraft"
version = "0.0.2"
description = "library of Gentoo Linux functionality"
authors = ["Tim Harder <radhermit@gmail.com>"]
homepage = "https://github.com/pkgcraft/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft"
documentation = "https://github.com/pkgcraft/pkgcraft"
readme = "README.md"
license = "MIT"
edition = "2018"
autotests = false

[lib]
name = "pkgcraft"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[[test]]
name = "integration"
path = "tests/lib.rs"

[dependencies]
once_cell = "1.8.0"
peg = "0.7"
regex = "1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"
maplit = "1.0.2"

[[bench]]
name = "bench"
harness = false
