name: audit

on:
  schedule:
    - cron: '0 6 * * 0'
  push:
    tags-ignore: ['**']
    paths:
      - "Cargo.lock"
      - ".github/workflows/audit.yml"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
