name: audit

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scallop
        uses: actions/checkout@v3
        with:
          repository: pkgcraft/scallop
          path: scallop
          submodules: true

      - name: Move scallop into expected location
        run: mv scallop ../

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run cargo audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
