name: bench

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.54.0
        profile: minimal
        override: true

    - name: Update crates
      run: cargo update

    - name: Cache crates
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry/cache
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-

    - name: Run benchmarks
      run: |
        cargo install cargo-criterion
        cargo criterion
