name: bench

on:
  schedule:
    - cron: '37 6 13 * *'
  push:
    branches: ['**']
    paths:
      - "crates/*/benches/**"
      - ".github/workflows/bench.yml"
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust

    - name: Restore cache
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: |
          ~/.cargo/bin
          target
        key: ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}-${{ github.run_id }}
        restore-keys: ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-rust-

    - name: Remove old caches
      if: ${{ github.ref_name == 'main' && steps.restore-cache.outputs.cache-hit != 'true' }}
      continue-on-error: true
      run: |
        gh extension install actions/gh-actions-cache

        REPO=${{ github.repository }}
        BRANCH=${{ github.ref }}
        KEY=${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-rust-

        # find matching caches
        mapfile -t cache_keys < <( gh actions-cache list -R $REPO -B $BRANCH --key $KEY --sort created-at --order desc | cut -f 1 )

        # remove all matching caches
        for key in ${cache_keys[@]}
        do
          gh actions-cache delete $key -R $REPO -B $BRANCH --confirm
        done

        exit 0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install cargo-criterion
      run: |
        # ignore return value since `cargo install` errors out when already installed
        cargo install cargo-criterion || true

    - name: Install protoc for arcanist
      uses: taiki-e/install-action@protoc

    - name: Benchmark pkgcraft
      run: cargo criterion --all-features -p pkgcraft --color always --output-format quiet

    - name: Download gentoo repo
      run: |
        mkdir gentoo
        curl -L https://github.com/gentoo-mirror/gentoo/archive/73d0ee59ebd9.tar.gz | tar -xz --strip-components=1 -C gentoo
        echo "PKGCRUFT_BENCH_REPO=${GITHUB_WORKSPACE}/gentoo" >> $GITHUB_ENV

    - name: Benchmark pkgcruft
      run: cargo criterion --all-features -p pkgcruft --color always --output-format quiet

    - name: Save cache
      if: ${{ github.ref_name == 'main' && steps.restore-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/bin
          target
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
