name: CI

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: ['1.65.0', 'stable']

    steps:
    - name: Checkout pkgcraft
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@master
      id: rust
      with:
        toolchain: ${{ matrix.rust-version }}

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest

    - name: Build and run tests
      run: cargo nextest run --color always --all-features 

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pkgcraft
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust
      with:
        components: clippy, rustfmt

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Run rustfmt
      run: cargo fmt --check

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  bench:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pkgcraft
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Install cargo-criterion
      run: |
        # ignore return value since `cargo install` errors out when already installed
        cargo install cargo-criterion || true

    - name: Build
      run: cargo criterion --no-run

    - name: Benchmark
      if: github.ref_name == 'bench'
      run: cargo criterion --color always --output-format quiet
