name: CI

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: ['1.65.0', 'stable']

    steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-workspace
        submodules: recursive

    - name: Pull submodule updates
      run: git submodule update --recursive --remote

    - name: Get bash submodule status
      working-directory: scallop/bash
      run: echo "SCALLOP_BASH=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Remove current repo from workspace
      run: rm -rfv ${{ github.event.repository.name }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@master
      id: rust
      with:
        toolchain: ${{ matrix.rust-version }}

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest

    - name: Build and test
      run: cargo nextest run --color always --all-features -p ${{ github.event.repository.name }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-workspace
        submodules: recursive

    - name: Pull submodule updates
      run: git submodule update --recursive --remote

    - name: Get bash submodule status
      working-directory: scallop/bash
      run: echo "SCALLOP_BASH=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Remove current repo from workspace
      run: rm -rfv ${{ github.event.repository.name }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust
      with:
        components: clippy, rustfmt

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Run rustfmt
      run: cargo fmt --check -p ${{ github.event.repository.name }}

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -p ${{ github.event.repository.name }}

  bench:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-workspace
        submodules: recursive

    - name: Pull submodule updates
      run: git submodule update --recursive --remote

    - name: Get bash submodule status
      working-directory: scallop/bash
      run: echo "SCALLOP_BASH=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Remove current repo from workspace
      run: rm -rfv ${{ github.event.repository.name }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust

    - name: Set up rust cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ github.job }}-${{ runner.os }}-rust-${{ steps.rust.outputs.cachekey }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-rust-

    - name: Install cargo-criterion
      run: |
        # ignore return value since `cargo install` errors out when already installed
        cargo install cargo-criterion || true

    - name: Build
      run: cargo criterion --no-run -p ${{ github.event.repository.name }}

    - name: Benchmark
      if: github.ref_name == 'bench'
      run: cargo criterion --color always --output-format quiet -p ${{ github.event.repository.name }}
