name: pkgcraft-c-release

on:
  push:
    tags: [pkgcraft-c-*]
    branches: ['**']
    paths:
      - ".github/workflows/pkgcraft-c-release.yml"
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pkgcraft workspace
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust

    - name: Create vendored release tarball
      run: .ci/vendor-tarball pkgcraft-c

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: source
        path: ./*.tar.xz
        if-no-files-found: error
        retention-days: 3

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: source
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: source/*.tar.xz
        fail_on_unmatched_files: true
