name: pkgcraft-tools-release

on:
  push:
    tags: [pkgcraft-tools-*]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout pkgcraft workspace
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up rust toolchain
      uses: dtolnay/rust-toolchain@stable
      id: rust

    - name: Create vendored release tarball
      run: .ci/vendor-tarball pkgcraft-tools

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pkgcraft-tools
        path: target/package/${{ github.ref_name }}.tar.xz
        if-no-files-found: error
        retention-days: 3

    - name: Create GitHub release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/package/${{ github.ref_name }}.tar.xz
        fail_on_unmatched_files: true
